import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '@/components/Card'
import cards from '@/Constants'

const inter = Inter({ subsets: ['latin'] })

const renderCards = (cards) => {
  return (
    cards.map((card) => {
      return (
        <Card
        key={card.id}
          img={card.img}
          title={card.title}
          description={card.description}
          link={card.link}
          alt={card.alt}
        />
      );
    }))
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Novels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} main`}>
        <div className='container'>
          {renderCards(cards)}
        </div>
      </main>
    </>
  )
}
